window.TACKLEBOX_ADVISOR = {
  targets: {
    fresh: [["general","Mixed freshwater"],["bass","Bass and pike"],["walleye-panfish","Walleye and panfish"],["trout","Trout"],["catfish","Catfish"]],
    salt: [["general","Mixed saltwater"],["striper-bluefish","Striped bass and bluefish"],["fluke","Fluke"],["sheeps","Sheepshead"],["inshore-game","Redfish, trout, and snook"],["offshore","Offshore species"]]
  },
  structures: {
    fresh: [["open","Open water or bank"],["vegetation","Grass or pads"],["wood-rock","Wood, rock, or docks"],["deep-current","Deep water or current"]],
    salt: [["open-beach","Open beach or surf"],["inlet-current","Inlet or current seam"],["bridge-jetty","Bridge, jetty, or piling"],["bay-flat","Bay, flat, or marsh"],["deep","Reef, wreck, or deep water"]]
  },
  forage: {
    fresh: [["small-bait","Small baitfish"],["large-bait","Large baitfish"],["invertebrate","Crawfish, insects, or worms"],["unknown","Unknown"]],
    salt: [["sand-eel","Sand eels or thin bait"],["small-bait","Small baitfish"],["bunker-mullet","Bunker, mullet, or large bait"],["crab-shrimp","Crab, shrimp, or sand fleas"],["unknown","Unknown"]]
  },
  profiles: [
    {water:"fresh",technique:"general-spin",targets:["general","bass","walleye-panfish"],tags:["stable","clear","stained","calm","moderate","open","small-bait","unknown","day"],lure:"Paddle-tail swimbait",presentation:"Cover a high-percentage edge with a steady retrieve, then slow-roll or pause when contact drops.",why:"A medium spinning system covers broad freshwater conditions without forcing a specialized presentation."},
    {water:"fresh",technique:"power-bass",targets:["general","bass"],tags:["warming","stained","muddy","moderate","strong","vegetation","wood-rock","large-bait","day"],lure:"Spinnerbait",presentation:"Run a visible, vibration-heavy bait beside cover and make repeated deflections instead of random open-water casts.",why:"Wind, reduced visibility, and cover favor a presentation fish can track and tackle that controls them quickly."},
    {water:"fresh",technique:"finesse",targets:["general","bass","walleye-panfish"],tags:["cooling","stable","clear","calm","open","wood-rock","unknown","day"],lure:"Ned rig",presentation:"Reduce size and speed, keep bottom contact, and lengthen pauses before changing locations.",why:"Clear, calm, pressured, or cooling conditions often favor a smaller controlled presentation."},
    {water:"fresh",technique:"trout-ul",targets:["trout"],tags:["cooling","stable","clear","calm","deep-current","small-bait","invertebrate","day"],lure:"Inline spinner",presentation:"Quarter across current or work the pool edge with the smallest lure that still tracks correctly.",why:"Light tackle and a controlled drift or swing fit trout-oriented water and smaller forage."},
    {water:"fresh",technique:"panfish",targets:["walleye-panfish"],tags:["warming","stable","clear","stained","calm","vegetation","wood-rock","small-bait","invertebrate","day"],lure:"1/32 to 1/8 oz jig",presentation:"Start shallow around cover, then count the jig down in small depth steps until bites appear.",why:"Small jigs efficiently probe depth and cover changes used by crappie, perch, and sunfish."},
    {water:"fresh",technique:"topwater-fresh",targets:["general","bass"],tags:["warming","stable","clear","stained","calm","moderate","vegetation","open","small-bait","large-bait","low"],lure:"Walking bait",presentation:"Start in low light over open lanes or vegetation edges and wait for the rod to load before setting.",why:"Warm, low-light, forage-driven conditions can bring active fish to the surface."},
    {water:"fresh",technique:"bottom-fresh",targets:["general","bass","walleye-panfish"],tags:["cooling","stable","clear","stained","moderate","strong","wood-rock","deep-current","small-bait","invertebrate","low"],lure:"Jig and minnow",presentation:"Use the lightest weight that repeats bottom contact and shorten lifts as water cools or current strengthens.",why:"Deep structure, rock, and current call for depth control and direct bottom feedback."},
    {water:"fresh",technique:"fresh-troll",targets:["general","walleye-panfish"],tags:["stable","open","deep-current","small-bait","large-bait","moderate","day"],lure:"Minnow crankbait",presentation:"Hold one speed and depth long enough to test it, then change only line-out or lure depth before speed.",why:"Trolling is useful when fish or forage are scattered across open or suspended water."},
    {water:"fresh",technique:"catfish",targets:["catfish"],tags:["warming","stable","stained","muddy","calm","moderate","deep-current","large-bait","invertebrate","low"],lure:"Fresh cut shad",presentation:"Place fresh bait on a channel edge or scent lane and let steady pressure load the circle hook.",why:"Natural scent and bottom-oriented rigs fit catfish behavior in reduced visibility and current."},
    {water:"salt",technique:"inshore-spin",targets:["general","fluke","inshore-game"],tags:["warming","stable","clear","stained","calm","moderate","bay-flat","small-bait","crab-shrimp","unknown","day"],lure:"3 to 4 in paddle-tail",presentation:"Match jighead weight to depth and current, then swim just above grass, oyster, or the channel edge.",why:"The all-around inshore system adapts efficiently across bays, flats, and moderate moving water."},
    {water:"salt",technique:"flats-sight",targets:["inshore-game"],tags:["warming","stable","clear","calm","bay-flat","small-bait","crab-shrimp","day"],lure:"Weedless paddle-tail",presentation:"Lead visible fish by several feet and keep the first presentation quiet and inside their travel lane.",why:"Clear, calm, shallow water rewards stealth and accurate weedless presentation."},
    {water:"salt",technique:"inshore-structure",targets:["general","striper-bluefish","fluke","sheeps","inshore-game"],tags:["stable","cooling","stained","muddy","moderate","strong","inlet-current","bridge-jetty","small-bait","crab-shrimp","low"],lure:"Bucktail jig",presentation:"Cast or lower up-current, stay tight to the seam or structure face, and use immediate side pressure after the bite.",why:"Hard structure and moving water concentrate forage but demand abrasion resistance and fast control."},
    {water:"salt",technique:"inshore-wade",targets:["inshore-game"],tags:["warming","stable","clear","calm","bay-flat","small-bait","crab-shrimp","low"],lure:"1/8 to 1/4 oz weedless plastic",presentation:"Move quietly, fan-cast potholes and drain edges, and keep the lure above grass rather than plowing it.",why:"Protected shallow water favors light weedless tackle and a stealth-first approach."},
    {water:"salt",technique:"salt-surf",targets:["general","striper-bluefish","fluke"],tags:["warming","cooling","stained","muddy","moderate","strong","open-beach","inlet-current","sand-eel","small-bait","bunker-mullet","low"],lure:"Bucktail jig",presentation:"Fish the first trough, cut, or rip before chasing distance and adjust weight until the lure holds the intended layer.",why:"Surf and inlet decisions are driven by structure, sweep, and forage more than raw casting distance."},
    {water:"salt",technique:"pier-bait",targets:["general","fluke","sheeps","striper-bluefish"],tags:["stable","cooling","clear","stained","calm","moderate","slack","bridge-jetty","crab-shrimp","small-bait","day"],lure:"Carolina rig with shrimp or mullet",presentation:"Keep bait beside structure or the current edge and use a drop net instead of lifting fish by the rod.",why:"Vertical access and natural bait efficiently cover mixed species around pilings and pier edges."},
    {water:"salt",technique:"nearshore-jig",targets:["general","striper-bluefish","offshore"],tags:["stable","moderate","strong","deep","small-bait","large-bait","day"],lure:"Knife or speed jig",presentation:"Choose jig mass for depth and current, find the bait layer, and change cadence before color.",why:"Vertical jigging reaches concentrated bait and structure when drift and depth can be controlled safely."},
    {water:"salt",technique:"offshore-bottom",targets:["offshore"],tags:["stable","moderate","strong","deep","crab-shrimp","large-bait","day"],lure:"Knocker or fish-finder rig",presentation:"Use only enough weight to hold the zone and confirm depth, season, circle-hook, and release-device rules.",why:"Deep reef and wreck fishing requires bottom control, heavy leader, and regulation-aware handling."},
    {water:"salt",technique:"offshore-troll",targets:["offshore"],tags:["warming","stable","deep","large-bait","moderate","day"],lure:"Skirted trolling lure",presentation:"Run a simple controlled spread along bait, weed, or temperature edges and log speed when a bite occurs.",why:"Trolling covers broad open water when pelagic fish and forage are moving rather than structure-bound."}
  ],
  adjustments: {
    trend:{warming:"Test shallower or faster first, especially near newly active edges.",stable:"Hold a productive depth and cadence long enough to evaluate it.",cooling:"Slow the presentation, lengthen pauses, and favor stable depth or current breaks."},
    clarity:{clear:"Use a natural profile, longer leader where appropriate, and quieter entry.",stained:"Add contrast or vibration and keep the lure in the strike zone longer.",muddy:"Prioritize vibration, scent, silhouette, or close-range target casting."},
    wind:{calm:"Use stealth, lighter weight, and longer pauses.",moderate:"Fish the windward edge when safe and use enough weight for control.",strong:"Prioritize protected water and control. Do not force unsafe casts, wading, or boat travel."},
    current:{slack:"Slow down and work depth changes or wait for movement when the fishery depends on current.",moderate:"Use the lightest weight that repeatedly reaches the target layer.",strong:"Move to the soft edge and increase weight only enough to maintain control."},
    light:{day:"Use shade, depth, cover, or a natural presentation in bright conditions.",low:"Search shallower and use silhouette, vibration, or surface activity when conditions allow."},
    forage:{"small-bait":"Downsize to a compact baitfish profile.","large-bait":"Use a fuller profile without exceeding the rod or local forage.",invertebrate:"Keep a bottom-oriented profile moving slowly.","sand-eel":"Use a slender profile near the bottom or bait line.","bunker-mullet":"Use a larger swimmer, plug, or legal natural bait.","crab-shrimp":"Keep the presentation near bottom or tight to hard structure.",unknown:"Start with a compact natural profile and observe before changing size."}
  },
  trouble: {
    none:{label:"No specific problem",action:"Run the primary presentation through two high-percentage lanes before changing anything.",check:"If there is no sign of life after a deliberate test, change depth before lure family."},
    "no-contact":{label:"No bites or contact",action:"Change one variable: move shallower or deeper, or shift to the nearest current or cover edge.",check:"Give the new depth or lane a fair repeat before changing size or color."},
    "short-strikes":{label:"Short strikes",action:"Reduce speed or size and add a brief pause without changing the whole rig.",check:"Confirm hooks are sharp and the trailer or bait runs straight."},
    fouling:{label:"Grass or debris fouling",action:"Use a weedless profile, hold the rod higher, or reduce weight so the lure rides above the fouling layer.",check:"Inspect the lure after every cast until it returns clean consistently."},
    "no-bottom":{label:"Cannot hold bottom",action:"Move to the softer current edge, shorten line angle, then add the smallest practical weight increase.",check:"Stop if required weight exceeds the rod, rig, or safe casting limit."},
    snagging:{label:"Repeated snags",action:"Change cast angle and lift earlier. Use a compact or weedless presentation before abandoning the area.",check:"Do not keep losing tackle on the same path. Re-map the obstacle from another angle."},
    "bait-stolen":{label:"Bait stolen",action:"Downsize bait, expose the hook correctly, and shorten the inspection interval.",check:"If small fish persist, move bait off bottom or use a tougher legal bait."},
    refusal:{label:"Fish visible but refusing",action:"Lead farther, reduce splash and profile, and make one natural pass without repeated casts on the fish.",check:"Rest the fish or change angle before trying another color."}
  },
  procedureByTarget:{"striper-bluefish":"striper-bucktail",fluke:"fluke-bucktail",sheeps:"sheeps-crab"},
  caveat:"This is a transparent pattern match, not a prediction. Local forage, regulations, access, and safety override the suggestion. Change one variable at a time and record what produces contact."
};