window.TACKLEBOX_DATA = {
  techniques: [
    {id:"general-spin",name:"Everyday Spinning",water:"fresh",group:"Spinning",access:["bank","boat","kayak"],seasons:["winter","spring","summer","fall"],species:["Bass","Walleye","Perch","Light catfish"],summary:"The first setup to own: light enough for finesse, enough backbone for most inland fish.",peak:"Spring through fall; slow and deep at winter midday",rig:{Rod:"6 ft 6 in–7 ft, Medium, Fast",Reel:"2500–3000 spinning",Mainline:"8–15 lb braid",Leader:"6–12 lb fluorocarbon, 18–36 in"},lures:[{name:"Paddle-tail swimbait",when:"Spring warming, summer shade, fall baitfish; steady swim or slow-roll."},{name:"1/8–3/8 oz jig",when:"Year-round; hop bottom in cold water, swim it when fish chase."},{name:"Small crankbait",when:"Spring and fall around rock, wood, and active fish."},{name:"Live minnow",when:"Cold water or neutral walleye, perch, and bass where legal."}],tip:"Choose by the rod’s lure rating and reel capacity, not the reel-size number alone."},
    {id:"power-bass",name:"Power Bass & Cover",water:"fresh",group:"Casting",access:["bank","boat","kayak"],seasons:["spring","summer","fall"],species:["Largemouth bass","Smallmouth bass","Pike"],summary:"Accurate casts, heavier line, and fast control around grass, wood, docks, and rock.",peak:"Pre-spawn through fall; strongest when fish chase or bury in cover",rig:{Rod:"7–7 ft 3 in, Medium-Heavy, Fast",Reel:"150–200 baitcaster, 7:1 class",Mainline:"14–20 lb fluoro or 40–65 lb braid",Leader:"Usually direct; wire for toothy fish"},lures:[{name:"Spinnerbait",when:"Wind, stained water, spring and fall; roll beside cover."},{name:"Swim or vibrating jig",when:"Spring through fall over grass and along edges."},{name:"Square-bill crankbait",when:"Spring/fall deflection around shallow cover; use Moderate action."},{name:"Texas or punch rig",when:"Summer vegetation and dense cover; heavy braid for mats."}],tip:"Power and action are separate. Fast suits single hooks; moderate keeps trebles pinned."},
    {id:"finesse",name:"Finesse & Cold Front",water:"fresh",group:"Finesse",access:["bank","boat","kayak"],seasons:["winter","spring","summer","fall"],species:["Bass","Walleye","Panfish"],summary:"Small, controlled presentations for clear water, pressure, cold fronts, and inactive fish.",peak:"Year-round problem solver; especially winter and post-front",rig:{Rod:"6 ft 9 in–7 ft 2 in, Medium-Light/Medium, Fast",Reel:"2500–3000 spinning",Mainline:"8–15 lb braid",Leader:"4–8 lb fluorocarbon"},lures:[{name:"Ned rig",when:"Cold or clear water; crawl, drag, or dead-stick."},{name:"Drop shot",when:"Suspended or pressured fish in summer and winter."},{name:"Shaky head",when:"Rock, points, and sparse cover spring through fall."},{name:"Wacky stick worm",when:"Spawn and post-spawn around docks and shallow cover."}],tip:"Let the smooth drag protect light leader. Do not compensate with an oversized reel."},
    {id:"trout-ul",name:"Trout & Ultralight",water:"fresh",group:"Spinning",access:["bank","kayak"],seasons:["winter","spring","summer","fall"],species:["Rainbow trout","Brown trout","Brook trout","Panfish"],summary:"A light, forgiving outfit for small streams, stocked lakes, and delicate presentations.",peak:"Spring and fall; summer only in cool water and low-light windows",rig:{Rod:"5 ft 6 in–7 ft, Ultralight/Light, Fast",Reel:"1000–2500 spinning",Mainline:"4–6 lb mono or fluoro",Leader:"4–6 lb fluoro if using braid"},lures:[{name:"Inline spinner",when:"Spring/fall search bait; quarter across current."},{name:"Small spoon",when:"Lakes, wind, and deeper pools; excellent fall option."},{name:"Floating dough bait",when:"Stocked lakes on a bottom rig where legal."},{name:"Worm or micro-jig",when:"Year-round; drift naturally or work slowly in winter."}],tip:"Avoid targeting temperature-stressed trout in warm water. Follow local guidance and handle quickly."},
    {id:"panfish",name:"Panfish & Crappie",water:"fresh",group:"Float & Jig",access:["bank","boat","kayak"],seasons:["winter","spring","summer","fall"],species:["Bluegill","Crappie","Yellow perch"],summary:"Light line and tiny offerings reveal bites and make common fish genuinely sporting.",peak:"Spring shallow spawn; fall schooling; summer shade and deep brush",rig:{Rod:"5 ft 6 in–7 ft, Ultralight/Light, Fast",Reel:"1000–2000 spinning",Mainline:"2–6 lb mono or fluoro",Leader:"Optional 4 lb fluoro"},lures:[{name:"1/32–1/8 oz tube or marabou jig",when:"All year; vertical in winter, cast shallow in spring."},{name:"Worm or waxworm under float",when:"Spring shallows and family-friendly bank fishing."},{name:"Small live minnow",when:"Crappie around brush, docks, and suspended schools."},{name:"Beetle spin or tiny crank",when:"Summer/fall searching for active schools."}],tip:"Use only enough float and weight to cast. Excess hardware hides delicate bites."},
    {id:"topwater-fresh",name:"Freshwater Topwater",water:"fresh",group:"Topwater",access:["bank","boat","kayak"],seasons:["spring","summer","fall"],species:["Bass","Pike"],summary:"Surface presentations for low light, warm water, schooling forage, and heavy vegetation.",peak:"Late spring through early fall; dawn, dusk, and overcast windows",rig:{Rod:"6 ft 8 in–7 ft 3 in, M–H by lure",Reel:"150–200 baitcaster, 7:1+",Mainline:"15–20 lb mono or 40–65 lb braid",Leader:"No sinking fluoro ahead of walking baits"},lures:[{name:"Walking bait",when:"Calm open water, summer/fall bait schools."},{name:"Popper",when:"Late spring around pockets and cover; pause longer in cool water."},{name:"Hollow frog",when:"Summer mats, pads, and dense surface grass."},{name:"Buzzbait",when:"Warm, stained, windy water along edges and laydowns."}],tip:"Wait until the rod loads before setting. An immediate reaction often pulls the lure away."},
    {id:"bottom-fresh",name:"Bottom Contact & Jigging",water:"fresh",group:"Bottom",access:["bank","boat","kayak"],seasons:["winter","spring","summer","fall"],species:["Walleye","Bass","Smallmouth"],summary:"High-sensitivity rigs for rock, channels, ledges, river seams, and deep structure.",peak:"Spring rivers, summer structure, fall humps, and winter vertical work",rig:{Rod:"6 ft 6 in–7 ft 6 in, ML–MH, Fast",Reel:"2500 spin or 150 casting",Mainline:"8–20 lb braid/fluoro",Leader:"4–15 lb fluoro by cover"},lures:[{name:"Jig and minnow",when:"Spring rivers and cold-water walleye."},{name:"Blade bait or jigging minnow",when:"Late fall and winter, vertically or snap-jigged."},{name:"Carolina rig",when:"Summer bass on points and ledges."},{name:"Ned or drop shot",when:"Pressure, rock, and inactive fish year-round."}],tip:"Use the lightest weight that maintains bottom contact. Current and depth set the weight."},
    {id:"fresh-troll",name:"Freshwater Trolling",water:"fresh",group:"Trolling",access:["boat","kayak"],seasons:["spring","summer","fall"],species:["Walleye","Lake trout","Landlocked salmon","Striped bass"],summary:"Repeatable depth and speed control for scattered, suspended, or roaming fish.",peak:"Summer suspended schools and fall feeding; spring shallow flats",rig:{Rod:"7 ft 10 in–10 ft, M–MH, Moderate-Fast",Reel:"Line-counter conventional preferred",Mainline:"10–17 lb mono or braid",Leader:"10–12 lb fluoro, 6–12 ft"},lures:[{name:"Minnow crankbait",when:"Spring shallows and night walleye."},{name:"Deep-diving crankbait",when:"Summer breaklines and suspended fish."},{name:"Bottom bouncer + crawler harness",when:"Summer/fall bottom-oriented walleye."},{name:"Trolling spoon",when:"Open-water trout and salmon near bait."}],tip:"Speed, line out, lure dive curve, and current work together. Log all four when bites happen."},
    {id:"catfish",name:"Catfish & Natural Bait",water:"fresh",group:"Bait",access:["bank","boat","kayak"],seasons:["winter","spring","summer","fall"],species:["Channel catfish","Blue catfish","Flathead catfish"],summary:"Durable tackle, circle hooks, and fresh bait for bottom, drift, and suspended rigs.",peak:"Spring channel cats; summer nights for blues and flatheads; fall feeding",rig:{Rod:"7–8 ft, MH–H, Moderate",Reel:"4000–6000 spin or 300 conventional",Mainline:"20–65 lb mono/braid by size",Leader:"20–50 lb abrasion-resistant mono"},lures:[{name:"Fresh cut shad",when:"Blue and channel cats spring through fall."},{name:"Nightcrawler",when:"Channel cats in spring and after warm rain."},{name:"Live legal baitfish",when:"Warm-season flatheads near cover; obey bait rules."},{name:"Slip or Santee rig",when:"Still water or drifting; keep bait near bottom."}],tip:"With circle hooks, reel into steady pressure. Do not make a hard sweeping hookset."},
    {id:"inshore-spin",name:"All-Around Inshore",water:"salt",group:"Inshore",access:["bank","boat","kayak"],seasons:["winter","spring","summer","fall"],species:["Redfish","Speckled trout","Flounder","Snook"],summary:"The coastal workhorse for soft plastics, corks, spoons, live bait, and shallow hardbaits.",peak:"Spring and fall transitions; summer dawn/dusk; winter channels",rig:{Rod:"7–7 ft 6 in, Medium, Fast",Reel:"2500–4000 salt-capable spinning",Mainline:"15–20 lb braid",Leader:"20–25 lb fluorocarbon, 18–30 in"},lures:[{name:"3–4 in paddle-tail",when:"All year; lighter heads shallow, heavier in current."},{name:"Live shrimp under popping cork",when:"Spring through fall over grass and oyster."},{name:"Suspending twitchbait",when:"Cool spring/fall water for trout and snook."},{name:"Gold weedless spoon",when:"Stained water, grass, and searching for redfish."}],tip:"Moving water outranks the clock. Fish drains on falling tide and newly flooded edges on rising tide."},
    {id:"flats-sight",name:"Flats Sight-Fishing",water:"salt",group:"Inshore",access:["boat","kayak"],seasons:["winter","spring","summer","fall"],species:["Redfish","Bonefish","Permit","Snook"],summary:"Quiet approach, long accurate casts, and weedless presentations to fish you can see.",peak:"Fall and spring; winter midday on warming flats; summer first light",rig:{Rod:"7–7 ft 6 in, M/MH, Fast",Reel:"2500–3500 sealed spinning",Mainline:"15–20 lb braid",Leader:"20–30 lb fluoro, 24–36 in"},lures:[{name:"Weedless paddle-tail",when:"Grass flats and cruising fish all year."},{name:"Gold or copper spoon",when:"Stained water and low light; especially redfish."},{name:"Live shrimp or crab",when:"Selective fish and clear water where legal."},{name:"Walking topwater",when:"Warm dawn/dusk before surface glare builds."}],tip:"Lead the fish by several feet. A lure landing on its head usually ends the opportunity."},
    {id:"inshore-structure",name:"Docks, Bridges & Jetties",water:"salt",group:"Structure",access:["bank","boat","pier"],seasons:["winter","spring","summer","fall"],species:["Snook","Striped bass","Redfish","Sheepshead","Bluefish"],summary:"Heavier leader and immediate control keep fish clear of pilings, rock, cable, and barnacles.",peak:"Moving tide; warm-season night lights; spring/fall migrations; winter sheepshead",rig:{Rod:"7–8 ft, MH/H, Fast",Reel:"3500–5000 spinning",Mainline:"20–30 lb braid",Leader:"30–50 lb fluoro; wire for toothy fish"},lures:[{name:"Bucktail jig",when:"Current seams and jetty bases year-round."},{name:"Live shrimp or baitfish",when:"Eddies, bridge lights, and inlet current."},{name:"Suspending jerkbait",when:"Cooler water or night shadow lines."},{name:"Crab on circle hook",when:"Winter/spring sheepshead around hard structure."}],tip:"Cast up-current and work the seam. Keep pressure immediately, but never lock drag beyond safe line and rod limits."},
    {id:"inshore-wade",name:"Wading & Backcountry",water:"salt",group:"Inshore",access:["bank","kayak"],seasons:["winter","spring","summer","fall"],species:["Redfish","Speckled trout","Flounder"],summary:"A light, minimal kit for stealth and access across flats, marshes, and protected creeks.",peak:"Spring/fall; Texas year-round; summer low light",rig:{Rod:"6 ft 6 in–7 ft 3 in, ML/M, Fast",Reel:"2500–3000 spinning",Mainline:"10–15 lb braid",Leader:"15–20 lb fluoro"},lures:[{name:"1/8–1/4 oz weedless plastic",when:"Clear shallow water and grass."},{name:"Small spoon",when:"Wind, stained water, and searching."},{name:"Topwater plug",when:"Low-light warm water."},{name:"Popping cork + shrimp",when:"Deeper potholes and stained water."}],tip:"Wear suitable footwear and a PFD where required. Know tide, return route, bottom, current, and local hazards before entering."},
    {id:"salt-surf",name:"Surf Casting",water:"salt",group:"Surf",access:["surf","bank"],seasons:["spring","summer","fall","winter"],species:["Striped bass","Red drum","Pompano","Bluefish","Whiting"],summary:"Long rods and weather-resistant reels carry plugs or bait beyond breakers and control fish in wash.",peak:"Spring/fall migration north; fall bull reds; cool-season pompano south",rig:{Rod:"9–11 ft, MH/H surf",Reel:"5000–8000 spinning",Mainline:"30–40 lb braid",Leader:"30–50 lb mono/fluoro, 3–4 ft"},lures:[{name:"Bucktail jig",when:"Rips, inlets, and migrating stripers spring/fall."},{name:"Metal spoon or casting jig",when:"Wind and distance; bluefish during spring/fall runs, Spanish and king mackerel in roughly 68°F+ coastal water."},{name:"Fish-finder rig + cut bait",when:"Red drum and stripers; circle-hook rules may apply."},{name:"Sand flea rig",when:"Pompano and whiting in warm-region surf."}],tip:"Read troughs, cuts, points, and bars before casting. Bigger distance is useless if fish are in the first trough."},
    {id:"pier-bait",name:"Pier & Jetty Bait Fishing",water:"salt",group:"Bait",access:["pier","bank"],seasons:["spring","summer","fall","winter"],species:["Sheepshead","Flounder","Redfish","Striped bass","Mackerel"],summary:"Vertical access to current, pilings, and mixed species with simple live- or cut-bait rigs.",peak:"Spring/fall migrations; winter structure fish; summer dawn/night",rig:{Rod:"7–9 ft, M/MH",Reel:"4000–6000 spinning",Mainline:"20–30 lb braid",Leader:"25–50 lb species/structure dependent"},lures:[{name:"Carolina rig + shrimp/mullet",when:"Flounder and redfish near bottom."},{name:"Crab or shrimp beside piling",when:"Sheepshead in cool months."},{name:"Sabiki rig",when:"Legal baitfish collection or small mackerel; follow local rules."},{name:"Metal jig",when:"Surface schools and current."}],tip:"Carry a landing net or drop net sized for the height. Never lift a substantial fish by rod and line."},
    {id:"nearshore-jig",name:"Nearshore Vertical Jigging",water:"salt",group:"Jigging",access:["boat","kayak"],seasons:["spring","summer","fall"],species:["Snapper","Grouper","Amberjack","Striped bass","Mackerel"],summary:"Compact jigs reach reefs, wrecks, and bait schools while the rod works directly beneath the boat.",peak:"Species and region dependent; best when bait and current align",rig:{Rod:"6–7 ft, MH/H jigging",Reel:"5000–8000 spin or 300–400 conventional",Mainline:"30–65 lb braid",Leader:"40–80 lb mono/fluoro"},lures:[{name:"Knife or speed jig",when:"Active pelagics and deep bait; fast cadence."},{name:"Slow-pitch jig",when:"Neutral fish and broad depth coverage."},{name:"Bucktail or soft-plastic jig",when:"Shallower reefs, stripers, and bottom edges."},{name:"Live bait on circle hook",when:"When permitted and artificials are ignored."}],tip:"Match jig mass to depth and current, not target size alone. Use a PFD and know kayak/offshore limits."},
    {id:"offshore-bottom",name:"Offshore Bottom Fishing",water:"salt",group:"Bottom",access:["boat"],seasons:["spring","summer","fall","winter"],species:["Snapper","Grouper","Sea bass","Tilefish"],summary:"High-capacity conventional tackle, circle hooks, and enough weight to hold reef or wreck structure.",peak:"Regulation and region drive access; current and weather drive the day",rig:{Rod:"6–7 ft, Heavy, Moderate-Fast",Reel:"300–500 conventional",Mainline:"50–80 lb braid",Leader:"60–100 lb mono/fluoro"},lures:[{name:"Knocker or fish-finder rig",when:"Natural bait close to reef structure."},{name:"Chicken rig",when:"Multi-hook rules allow and smaller bottom species school."},{name:"Heavy jig",when:"Active fish or avoiding bait stealers."},{name:"Cut squid, fish, or legal live bait",when:"Match local forage and regulations."}],tip:"Confirm seasons, depth limits, venting/descending-device rules, and circle-hook requirements before leaving."},
    {id:"offshore-troll",name:"Offshore Trolling",water:"salt",group:"Trolling",access:["boat"],seasons:["spring","summer","fall"],species:["Tuna","Mahi-mahi","Wahoo","King mackerel","Billfish"],summary:"A coordinated spread covers water for fast pelagics; boat handling and drag discipline matter as much as tackle.",peak:"Migration and water temperature vary widely by coast; follow local reports and regulations",rig:{Rod:"5 ft 6 in–7 ft trolling rod",Reel:"30–50 class conventional",Mainline:"30–80 lb mono or braid backing",Leader:"50–150+ lb mono; wire where appropriate"},lures:[{name:"Skirted trolling lure",when:"Bluewater pelagics around temperature breaks and weed lines."},{name:"Diving plug",when:"Wahoo, tuna, and kingfish at controlled speed."},{name:"Rigged ballyhoo",when:"Broad offshore use where legal and available."},{name:"Planer/spoon rig",when:"King mackerel and nearshore pelagics."}],tip:"Never wrap line around a hand or body. Offshore work requires experienced crew, safety gear, communications, and weather discipline."}
  ],
  quiver:[
    {name:"Core spinning",spec:"6 ft 6 in–7 ft • Medium • Fast • 2500–3000",use:"Freshwater finesse through general duty, plus protected light inshore when the reel is salt-capable."},
    {name:"Power casting",spec:"7–7 ft 3 in • Medium-Heavy • Fast/Mod-Fast • 150–200",use:"Bass cover, larger single-hook lures, pike, and precision work that overmatches the core spinner."},
    {name:"Heavy salt",spec:"8–10 ft surf or 7 ft boat rod • 5000–8000 spin / 300–400 conventional",use:"Surf, jetties, nearshore, bottom fishing, strong current, and fish that need capacity and sustained drag."}
  ],
  seasons:[
    {name:"Winter",signal:"Slow & stable",points:["Fresh: small jigs, finesse plastics, blade baits, live bait; work deepest stable water slowly.","Salt: channels, holes, warm midday flats, and hard structure; sheepshead and black drum often shine.","Best clock: midday warming. Avoid forcing a fast reaction bite."]},
    {name:"Spring",signal:"Warming & moving",points:["Fresh: jerkbaits, spinnerbaits, shallow cranks, jigs, and live minnows as fish stage and move shallow.","Salt: paddle-tails, corked shrimp, twitchbaits, and spoons on warming flats and estuary edges.","Protect spawning fish and follow seasonal closures."]},
    {name:"Summer",signal:"Low light & depth",points:["Fresh: topwater at dawn, deep cranks, worms, drop shots, and shade/flow by day.","Salt: dawn/dusk flats, night lights, moving tide, surf troughs, or deeper reefs.","Heat raises fish-handling risk; minimize air exposure."]},
    {name:"Fall",signal:"Forage & migration",points:["Fresh: lipless cranks, swimbaits, spinnerbaits, topwater, and trolling around bait schools.","Salt: mullet/bait runs trigger plugs, metals, bucktails, spoons, and live bait from bay to surf.","Often the broadest all-day reaction-bait window."]}
  ],
  notes:[
    {title:"Regulations first",text:"Verify license, season, slot/size, bag, bait, circle-hook, lead, and protected-species rules with the current agency source."},
    {title:"Wear the PFD",text:"Boat, kayak, current, surf, and cold-water risk do not care how experienced you are. Wear the correct, serviceable flotation."},
    {title:"Respect salt",text:"After salt exposure, lightly rinse rod, reel, line, lures, and tools with fresh water; dry fully and back off stored drag."},
    {title:"Retie before failure",text:"Check leader after fish, rock, oysters, pilings, teeth, and snags. Replace at the first nick or clouded abrasion."},
    {title:"Match hook behavior",text:"Set J-hooks; with circle hooks, let the fish load the rod and reel into pressure. Check local mandates."},
    {title:"Stop for lightning",text:"Carbon rods conduct electricity. Secure rods and leave exposed water before a storm reaches you."}
  ],
  sources:[
    {name:"Take Me Fishing / RBFF — Fishing resources",url:"https://www.takemefishing.org/how-to-fish/fishing-resources/"},
    {name:"NOAA Fisheries — Regulations and conservation",url:"https://www.fisheries.noaa.gov/"},
    {name:"U.S. Coast Guard — Recreational boating safety",url:"https://uscgboating.org/"},
    {name:"U.S. Fish & Wildlife Service — Fishing and lead-tackle context",url:"https://www.fws.gov/"},
    {name:"Atlantic States Marine Fisheries Commission",url:"https://www.asmfc.org/"},
    {name:"Wired2Fish — Walleye techniques",url:"https://www.wired2fish.com/walleye/how-to-catch-walleye"},
    {name:"Bassmaster — Finesse rod selection",url:"https://www.bassmaster.com/how-to/news/choosing-your-finesse-fishing-rod/"},
    {name:"Salt Water Sportsman — Jetty fishing",url:"https://www.saltwatersportsman.com/howto/jetty-fishing-tips/"},
    {name:"Texas Saltwater Fishing Magazine — Jetty tackle",url:"https://www.texassaltwaterfishingmagazine.com/fishing/jetty-tackle"}
  ]
};

window.TACKLEBOX_DATA.nj = {
  defaultSpecies: "striper",
  species: {
    striper: {
      label: "Striped bass",
      subtitle: "Spring run · fall migration · surf, inlet, and bay",
      intro: "Follow bait and moving water from the Raritan and Delaware systems to inlet rips and the ocean wash.",
      fields: [
        {id:"season",label:"Season",options:[["spring","Spring run"],["summer","Summer / night"],["fall","Fall run"],["winter","Winter holdover"]]},
        {id:"access",label:"Access",options:[["surf","Surf / beach"],["jetty","Jetty / inlet"],["bay","Back bay / estuary"],["boat","Boat / kayak"],["pier","Pier / bridge"]]},
        {id:"signal",label:"Bait or condition",options:[["bunker","Adult bunker"],["peanuts","Peanut bunker"],["mullet","Mullet"],["sandeel","Sand eels"],["spearing","Spearing / rainfish"],["eel","Night / live eel"],["rough","Dirty / rough water"],["calm","Clean / calm"]]}
      ],
      plays: [
        {id:"spring-bunker",name:"Spring bunker run",match:{season:["spring"],access:["bay","boat"],signal:["bunker"]},lure:"Bunker-profile soft bait, large swimmer, or legally presented fresh bunker",rig:"30–50 lb braid, 40–50 lb leader; inline circle hook whenever fishing bait",retrieve:"Slow and deliberate. Live-line naturally or keep a soft bait beside the school.",why:"Large spring bass key on adult menhaden in bays and river mouths.",caution:"Verify current NJ season, slot, possession, bunker, and registry rules before fishing."},
        {id:"spring-surf",name:"Early surf and inlet",match:{season:["spring"],access:["surf","jetty"],signal:["rough","calm"]},lure:"Bucktail with trailer, minnow plug, or clam/bloodworm where legal",rig:"9–10 ft surf rod, 20–30 lb braid, 30–40 lb leader; circle hook for bait",retrieve:"Sweep troughs and cuts slowly; let current swing a bucktail through the seam.",why:"Migrating fish pause at warmer outflows, cuts, and inlet edges.",caution:"Do not assume calendar dates. Check NJDEP Marine Fisheries before every trip."},
        {id:"summer-night",name:"Summer night current",match:{season:["summer"],access:["jetty","bay","pier"],signal:["eel","calm"]},lure:"Dark needlefish, slim swimmer, bucktail, or live eel",rig:"20–30 lb braid, 30–50 lb abrasion leader; inline circle hook for eel",retrieve:"Dead-slow and straight. Let the tide sweep across shadow lines and inlet seams.",why:"Low light, cooler water, and current concentrate summer resident fish.",caution:"Carry light, flotation, and traction; never turn your back to inlet surge."},
        {id:"fall-mullet",name:"September mullet run",match:{season:["fall"],access:["surf","jetty"],signal:["mullet"]},lure:"Pencil popper, walking plug, or mullet-profile swimmer",rig:"9–11 ft surf outfit, 30 lb braid, 30–40 lb leader",retrieve:"Walk or chug on top, then slow a swimmer through the wash after dark.",why:"Mullet travel tight to the beach and create a visible surface profile.",caution:"Work the first trough before casting beyond it."},
        {id:"fall-peanuts",name:"Peanut bunker blitz",match:{season:["fall"],access:["surf","boat","pier"],signal:["peanuts","spearing"]},lure:"Small epoxy jig, compact metal, or 4–6 in swimmer",rig:"20–30 lb braid with 30–40 lb leader",retrieve:"Match bait size; medium-fast through the school, then sink below surface chaos.",why:"Compact young-of-year bait often draws mixed-size bass close to shore.",caution:"Avoid treble-hook crowding during blitzes; give other anglers room."},
        {id:"fall-sandeel",name:"Late-fall sand eel pattern",match:{season:["fall"],access:["surf","jetty"],signal:["sandeel"]},lure:"Thin diamond jig or needlefish with a single teaser",rig:"30 lb braid, 40 lb leader; teaser 12–18 in ahead",retrieve:"Steady and low with occasional flutter or pause.",why:"A narrow profile and bottom-oriented retrieve match sand eels.",caution:"Use only one teaser and controlled casts around crowds."},
        {id:"rough-water",name:"Dirty-water search",match:{season:["spring","fall"],access:["surf","jetty"],signal:["rough"]},lure:"Dark or chartreuse bucktail, wide-wobble swimmer, or bait rig",rig:"Heavier leader and only enough weight to hold the strike zone",retrieve:"Slow, close, and in contact; use vibration and silhouette.",why:"Visibility falls, so profile and pressure waves matter more than detail.",caution:"White water can hide holes and sweep; retreat before conditions exceed your footing."},
        {id:"winter-holdover",name:"Winter holdover finesse",match:{season:["winter"],access:["bay","pier"],signal:["calm","spearing"]},lure:"Small paddletail or fluke-style plastic",rig:"Light jighead, 15–25 lb leader, balanced spinning outfit",retrieve:"Drag or dead-stick near the warmest stable water.",why:"Holdovers feed in short windows and rarely chase far.",caution:"Confirm open water and current rules; handle cold-stressed fish quickly."}
      ],
      rules:[
        "Atlantic Ocean, 0–3 nautical miles: open year-round; 28–31 in slot; 1 fish per person per day.",
        "Other NJ marine waters: March 1–December 31; 28–31 in slot; 1 fish per person per day.",
        "Delaware River, Calhoun Street Bridge downstream to Salem River: March 1–31 and June 1–December 31; closed April–May.",
        "Federal EEZ beyond 3 nautical miles: targeting, harvest, retention, and possession are prohibited.",
        "Inline circle hooks are required with bait. Gaffing and net take are prohibited. Free NJ saltwater registration is required for anglers 16+.",
        "2026 Bonus Program: one 24 to under-28 in fish per permit, May 15–December 31; immediate tagging and harvest reporting required."
      ],
      footer:"2026 summary from the NJ Marine Digest reprint on eRegulations, ASMFC, and eCFR. N.J.A.C. is binding law. Verify in-season NJDEP changes before every trip."
    },
    fluke: {
      label: "Fluke",
      subtitle: "Summer flounder · beaches, cuts, inlets, and channel edges",
      intro: "Keep a moving offering near bottom. Fluke face current and ambush forage crossing sand, troughs, cuts, and edges.",
      fields: [
        {id:"access",label:"Access",options:[["surf","Surf / beach"],["inlet","Inlet / rip"],["bay","Back bay / channel"],["pier","Pier / bulkhead"]]},
        {id:"drift",label:"Water movement",options:[["slow","Slack / slow"],["moderate","Moderate"],["fast","Fast / ripping"],["stationary","Anchored / stationary"]]},
        {id:"depth",label:"Depth or structure",options:[["shallow","Shallow trough / flat"],["edge","Channel edge"],["deep","Deep hole / inlet"],["structure","Bulkhead / rock edge"]]}
      ],
      plays: [
        {id:"surf-light",name:"Walk-and-cast beach bucktail",match:{access:["surf"],drift:["slow","moderate"],depth:["shallow"]},lure:"1/2–1 oz bucktail plus scented grub or strip bait",rig:"7–9 ft medium spinning rod, 10–20 lb braid, 20–30 lb leader; optional teaser",retrieve:"Cast diagonally, maintain bottom, lift-drop while walking the trough.",why:"Mobile anglers cover ambush lanes inside the first bar.",caution:"Measure every fish and verify the current NJ season, size, and possession rules."},
        {id:"surf-cut",name:"Cut and trough sweep",match:{access:["surf"],drift:["moderate","fast"],depth:["edge"]},lure:"1–2 oz bucktail with paddle-tail or scented trailer",rig:"Use the lightest head that repeatedly touches bottom",retrieve:"Cast up-current, follow the sweep, and pause beside the cut lip.",why:"Current funnels forage through cuts where fluke can pin it to sand.",caution:"Avoid wading across unseen cuts in moving surf."},
        {id:"inlet-rip",name:"Inlet rip bucktail",match:{access:["inlet"],drift:["fast"],depth:["deep","edge"]},lure:"2–4 oz bucktail or weighted fluke rig",rig:"20–30 lb braid, 30–40 lb abrasion leader; weight matched to current",retrieve:"Short controlled lifts while the rig sweeps the bottom edge.",why:"Heavy flow demands enough weight to stay in the feeding lane.",caution:"Inlet current, rocks, and boat traffic create serious hazards."},
        {id:"bay-drift",name:"Bay channel drift",match:{access:["bay"],drift:["moderate"],depth:["edge"]},lure:"Bucktail and teaser, or squid/spearing-style bait combination",rig:"1–2 oz bottom-contact rig on 15–20 lb braid",retrieve:"Tend bottom continuously; lift just enough to make the trailer swim.",why:"Channel edges combine current, forage, and depth changes.",caution:"Keep clear of marked navigation channels and moving vessels."},
        {id:"slow-finesse",name:"Slow-water finesse",match:{access:["bay","pier"],drift:["slow","stationary"],depth:["shallow","structure"]},lure:"Light jig with scented minnow, killie-style bait, or strip bait",rig:"1/4–3/4 oz jig, 15–25 lb leader",retrieve:"Subtle hops and long pauses; let tide animate the bait.",why:"Light tackle keeps a natural presentation when current cannot move a heavy rig.",caution:"Do not let a stationary bait bury into grass or debris."},
        {id:"pier-edge",name:"Pier and bulkhead edge",match:{access:["pier"],drift:["moderate","stationary"],depth:["structure","edge"]},lure:"High-low fluke rig or bucktail beside the edge",rig:"Sinker heavy enough to hold; landing net or drop net ready",retrieve:"Vertical lift-drop or short sweeps parallel to structure.",why:"Fluke use shade lines, pilings, and scoured edges as ambush points.",caution:"Never lift a substantial fish by rod and line from height."}
      ],
      rules:[
        "General NJ waters: May 4–September 25; 18 in minimum; 3 fish per person.",
        "Delaware Bay and tributaries: May 4–September 25; 17 in minimum; 3 fish per person.",
        "Island Beach State Park shore fishing: May 4–September 25; 16 in minimum; 2 fish per person.",
        "IBSP shore fishing means pier, jetty, beach, bank, or marsh access under the published rule.",
        "One legal-size fluke from the current daily catch may be filleted for bait; retain the intact rack for measurement."
      ],
      footer:"2026 measures from the NJ Marine Digest reprint on eRegulations. Regulations remain in effect until changed; verify NJDEP updates before fishing. Handle teeth and dorsal spines carefully."
    },
    sheeps: {
      label: "Sheepshead",
      subtitle: "Shore-access structure · jetties, bridges, pilings, and seawalls",
      intro: "This is not featureless-beach surf fishing. Find barnacle, mussel, crab, and current on hard structure, then fish vertically and react to a subtle bite.",
      fields: [
        {id:"structure",label:"Structure",options:[["jetty","Jetty / inlet rock"],["piling","Bridge / dock piling"],["wall","Bulkhead / seawall"],["mussel","Mussel bed / sod edge"]]},
        {id:"bait",label:"Bait",options:[["crab","Fiddler or green crab"],["flea","Sand flea"],["shrimp","Shrimp"],["mussel","Barnacle / mussel"],["clam","Clam"]]},
        {id:"tide",label:"Tide",options:[["moving","Moving water"],["slack","Slack water"],["warming","Warming midday"]]}
      ],
      plays: [
        {id:"jetty-crab",name:"Jetty crab drop",match:{structure:["jetty"],bait:["crab"],tide:["moving"]},lure:"Small whole or halved legal crab",rig:"Small strong short-shank hook, 20–30 lb abrasion leader, just enough weight to hold",retrieve:"Lower beside the rock face; hold bottom and set when taps become weight.",why:"Crabs naturally wash along barnacle-covered inlet rock.",caution:"Use cleated footwear where appropriate, watch swell, and retie after every rock contact."},
        {id:"piling-crab",name:"Piling scrape zone",match:{structure:["piling"],bait:["crab","shrimp"],tide:["moving","slack"]},lure:"Crab or fresh shrimp tight to the piling",rig:"Knocker or split-shot rig, short abrasion leader",retrieve:"Keep nearly vertical; detect the light scrape and pull away immediately.",why:"Sheepshead graze crustaceans directly from pilings.",caution:"Have a landing or drop net ready and keep hands clear of teeth and spines."},
        {id:"wall-finesse",name:"Seawall finesse",match:{structure:["wall"],bait:["shrimp","clam"],tide:["moving","warming"]},lure:"Fresh shrimp or clam piece",rig:"Light split shot, compact hook, 20–30 lb leader",retrieve:"Slowly walk the bait along shade, seams, and wall irregularities.",why:"A light rig presents naturally where heavy weight would snag.",caution:"Public access and bait rules vary; do not scrape protected or private structures."},
        {id:"mussel-edge",name:"Mussel-bed edge",match:{structure:["mussel"],bait:["mussel","crab"],tide:["moving","warming"]},lure:"Mussel, barnacle-style bait, or small crab",rig:"Short leader with enough weight for intermittent bottom contact",retrieve:"Hold at the hard-soft edge and lift only to clear snags.",why:"Shell beds supply forage and a defined edge in current.",caution:"Shell and oysters cut leader quickly; inspect after every drop."},
        {id:"sandflea-rock",name:"Sand flea along inlet rock",match:{structure:["jetty","wall"],bait:["flea"],tide:["moving"]},lure:"Fresh sand flea",rig:"Small stout hook and a compact bottom rig",retrieve:"Present tight to submerged rock and maintain direct feel.",why:"Sand fleas are a natural shore forage that can work where rock meets beach.",caution:"Sheepshead are a structure target here, not an open-sand roaming fish."},
        {id:"slack-precision",name:"Slack-tide precision",match:{structure:["piling","jetty"],bait:["crab","mussel"],tide:["slack"]},lure:"Small crab or fresh shellfish bait",rig:"Downsize sinker for a vertical natural fall",retrieve:"Hold still, watch line, and set on weight rather than repeated taps.",why:"Reduced flow lets a light bait remain beside the feeding face.",caution:"Verify current NJ species identification, season, size, and possession rules before retention."}
      ],
      rules:[
        "The 2026 NJ statewide summary table has no dedicated sheepshead entry.",
        "Do not infer that no other rule applies; verify current NJDEP regulations and emergency changes before harvest.",
        "NJ wanton-waste rules still apply: intentionally killed fish must be retained and may not be discarded."
      ],
      footer:"2026 Marine Digest summary-table finding only; N.J.A.C. and in-season changes remain binding. Sheepshead are primarily a hard-structure shore target. Barnacles, waves, teeth, and dorsal spines demand abrasion leader, traction, and careful handling."
    }
  },
  sources: [
    {name:"NJDEP Marine Fisheries",url:"https://dep.nj.gov/njfw/fishing/marine/"},
    {name:"ASMFC Atlantic Striped Bass",url:"https://www.asmfc.org/species/atlantic-striped-bass"},
    {name:"ASMFC Summer Flounder",url:"https://www.asmfc.org/species/summer-flounder"},
    {name:"NOAA Summer Flounder",url:"https://www.fisheries.noaa.gov/species/summer-flounder"},
    {name:"NOAA Atlantic Striped Bass",url:"https://www.fisheries.noaa.gov/species/atlantic-striped-bass"},
    {name:"Federal Striped Bass EEZ Rule",url:"https://www.ecfr.gov/current/title-50/chapter-VI/part-697/section-697.7"},
    {name:"2026 NJ Size and Possession Limits",url:"https://www.eregulations.com/newjersey/fishing/saltwater/state-size-possession-limits"},
    {name:"NJ Finfish Regulations and Wanton Waste",url:"https://www.eregulations.com/newjersey/fishing/saltwater/finfish-regulations/"}
  ]
};