window.TACKLEBOX_DATA.manual = {
  procedures: [
    {id:"striper-bucktail",species:"striper",title:"Bucktail the wash and inlet seam",when:"Surf cuts, inlet rips, dirty water, spring and fall",setup:"9–10 ft surf rod, 20–30 lb braid, 30–40 lb leader; 1/2–3 oz bucktail with pork-style or soft-plastic trailer",rig:"bucktail-teaser",knot:"loop",cast:["Identify the trough edge, cut, rip line, or down-current seam before casting.","Cast 30–45 degrees up-current, not straight across the flow.","Close the bail manually and count the jig down until it touches bottom or enters the target depth."],retrieve:["Point the rod 30–45 degrees toward the water and keep a slight bend in the tip.","Turn the handle only fast enough to keep the jig just above bottom; tap bottom occasionally.","Lift the tip 6–12 inches to clear rock, then lower while recovering slack.","Continue through the near wash; many bass strike at your feet."],hookset:"When the rod loads or the jig stops, reel tight and sweep firmly. Do not snap on slack line.",mistakes:"Using too much weight, retrieving above the fish, or ending the retrieve before the wash."},
    {id:"striper-paddletail",species:"striper",title:"Swim a paddletail or shad",when:"Bays, bridges, beach troughs, bunker and herring patterns",setup:"7–10 ft spinning rod, 20–30 lb braid, 25–40 lb leader; 4–9 in soft shad matched to forage",rig:"jighead",knot:"loop",cast:["Cast beyond the bait school, current seam, bridge shadow, or trough lip.","Feather the line before splashdown so the lure lands quietly and straight.","Count down one second at a time until the lure reaches the chosen level."],retrieve:["Use a slow, steady handle turn that keeps the tail working without rolling the body.","Add one short rod lift every 5–8 turns, then let the lure fall on controlled line.","In current, hold the lure in the seam and let flow provide most of the action."],hookset:"Keep reeling through the first bump. Sweep only after the rod gains steady weight.",mistakes:"Fishing too fast, using a jighead too heavy for the depth, or striking the first tail slap."},
    {id:"striper-minnow",species:"striper",title:"Fish a minnow swimmer",when:"Calm to moderate surf, back bays, bridge lights, spring and fall",setup:"20–30 lb braid, 25–40 lb leader; floating or shallow-running minnow plug",rig:"plug-leader",knot:"loop",cast:["Cast across and slightly up-current of the seam, bar, or shadow line.","Land beyond the target so the plug is swimming before it enters the strike zone."],retrieve:["Start with two turns to make the plug dig, then slow until it barely wobbles.","Keep the rod tip low in wind and higher over shallow rock.","Pause briefly beside current breaks or shadow edges, then resume without jerking."],hookset:"Let the rod load against the moving plug, then sweep while reeling.",mistakes:"Overworking the lure, retrieving faster at night, or using a snap that restricts action."},
    {id:"striper-metallip",species:"striper",title:"Crawl a metal-lip swimmer",when:"Night surf, boulder fields, bunker, mullet, and rough water",setup:"9–11 ft surf rod, 30 lb braid, 40–50 lb leader; metal-lip sized to water depth",rig:"plug-leader",knot:"loop",cast:["Cast beyond the whitewater, point, pocket, or boulder lane.","Take up slack and let the plug settle for one second before starting."],retrieve:["Retrieve painfully slow, just fast enough to feel a rhythmic thump.","Use the rod angle to steer over shallow rock or dig into a trough.","Pause for one heartbeat when the swimmer crosses a seam, then continue."],hookset:"Keep turning until the rod bends deeply; then sweep. Never jerk at the swirl.",mistakes:"Fishing too fast, selecting a swimmer that dives below the lane, or stopping after a missed strike."},
    {id:"striper-needle",species:"striper",title:"Needlefish and darter after dark",when:"Night tides, sand-eel patterns, inlets, strong current",setup:"30 lb braid, 40–50 lb leader; needlefish for straight water, darter for sweeping current",rig:"plug-leader",knot:"loop",cast:["Cast a needle parallel to a trough or across a bar; cast a darter up-current of the rip.","Allow a needle to settle to the desired level; begin a darter immediately in hard current."],retrieve:["Needle: slow straight retrieve with rare one-second pauses.","Darter: maintain tension and let current swing it through the seam; use minimal handle speed.","Keep the rod low and follow the lure with the tip so it does not skate."],hookset:"Reel into steady weight and sweep. A strike in darkness often feels like simple heaviness.",mistakes:"Adding constant twitches, losing contact in current, or shining lights across the water."},
    {id:"striper-darter",species:"striper",title:"Swing a darter through inlet current",when:"Night inlets, jetty rips, bridge outflow, strong current",setup:"9–10 ft rod, 30 lb braid, 40–50 lb leader; darter selected to current speed and depth",rig:"plug-leader",knot:"loop",cast:["Stand in a legal stable position down-current of the lane you want to cross.","Cast 30–45 degrees up-current so the plug has room to dig before reaching the seam.","Close the bail manually and recover slack immediately; do not let the darter tumble."],retrieve:["Hold the rod low and turn the handle just fast enough to feel the lure dig.","As current catches it, stop adding speed and follow the swing with the rod tip.","When it reaches the soft edge, pause for one heartbeat, then resume a slow crawl.","Finish the swing close to structure before recasting."],hookset:"A take usually feels like the plug stopped. Keep reeling until the rod bends, then sweep toward open water.",mistakes:"Casting straight down-current, reeling faster than the current, giving slack during the swing, or using a darter too deep for the lane."},
    {id:"striper-pencil",species:"striper",title:"Walk a pencil or spook",when:"Mullet, bunker, calm low light, visible feeds",setup:"8–10 ft rod, 20–30 lb braid, 30–40 lb leader; pencil, walker, or spook-style plug",rig:"plug-leader",knot:"loop",cast:["Cast past the bait or along the outer edge rather than into the middle of feeding fish.","Begin moving the plug as soon as it lands when bluefish or birds are present."],retrieve:["Hold the rod tip at waist height and make short downward taps while reeling slowly.","Use a steady left-right cadence; pause two seconds after a miss.","Vary speed only after fish show a preference."],hookset:"Ignore the splash. Keep working until line tightens, then sweep with the rod low.",mistakes:"Setting on the explosion, stopping the lure for too long in bluefish schools, or casting across another angler."},
    {id:"striper-popper",species:"striper",title:"Work a popper in whitewater",when:"Rough surf, daytime blitzes, disoriented bunker or mullet",setup:"Surf spinning outfit, 30–40 lb leader; cupped popper matched to wind",rig:"plug-leader",knot:"loop",cast:["Cast beyond the bar, point, or breaking bait so the plug crosses the edge.","Land with the rod tip high enough to keep line clear of the first wave."],retrieve:["Pull 6–12 inches to make one clear pop, then recover slack.","Use pop-pop-pause in broken water; use single pops and longer pauses in calm water.","Lower the tip and reel steadily if fish follow without committing."],hookset:"Wait for weight, reel down, and sweep.",mistakes:"Making nonstop noise, dragging the plug sideways, or using trebles in dense crowds."},
    {id:"striper-tin",species:"striper",title:"Tin and teaser for sand eels",when:"Late fall, distance, wind, thin forage",setup:"9–11 ft rod, 20–30 lb braid, 30–40 lb leader; thin metal with one teaser 12–18 in ahead",rig:"bucktail-teaser",knot:"improved-clinch",cast:["Use a smooth pendulum or overhead cast only after checking the full arc behind you.","Cast beyond the trough or sand-eel line, then count down to bottom."],retrieve:["Retrieve steadily just off bottom with one short lift every 6–10 turns.","Let the metal flutter for one second after each lift without giving full slack.","If birds are active, fish below them before burning the lure near the surface."],hookset:"Reel through taps and sweep when weight builds.",mistakes:"Using multiple teasers, retrieving above the forage, or casting a swinging teaser near people."},
    {id:"striper-eel",species:"striper",title:"Drift a live eel",when:"Summer and fall nights, inlets, bridges, boulder fields",setup:"20–30 lb braid, 40–50 lb leader, inline circle hook sized to bait",rig:"live-bait",knot:"improved-clinch",cast:["Hook the eel through both lips or the upper jaw with the point exposed.","Make a controlled lob up-current; never power-cast a live bait.","Close the bail and maintain light contact as the eel sinks and swings."],retrieve:["Let current carry the eel through the seam while reeling only enough to prevent bottom snags.","Lift slowly over rock and lower back into the lane.","If the eel balls up, reel in and straighten it before recasting."],hookset:"With an inline circle hook, point the rod at the fish and reel until fully loaded. Do not snap-set.",mistakes:"Power casting, burying the hook point, letting the eel wrap the leader, or using an offset hook."},
    {id:"striper-bunker",species:"striper",title:"Live-line or chunk bunker",when:"Raritan Bay, Delaware Bay, nearshore schools, spring and fall",setup:"30–50 lb braid, 40–60 lb leader, inline circle hook; fish-finder rig for chunks",rig:"fishfinder",knot:"improved-clinch",cast:["Live bunker: lob to the school edge or current seam and let it swim naturally.","Chunk: cast a fish-finder rig into a channel edge, point, or down-current scent lane.","Set the rod with a clear line path and drag appropriate for a circle hook."],retrieve:["Live bait: guide it away from the center of the school with gentle pressure.","Chunk: keep the sinker planted and line lightly tensioned; refresh bait when scent fades."],hookset:"Let the fish move off, then reel steadily until the rod loads. Never jerk a circle hook.",mistakes:"Snagging without checking current rules, casting into the school center, or leaving the rod unattended."},
    {id:"striper-clam",species:"striper",title:"Soak clam or cut bait in the surf",when:"Early spring, dirty water, cold surf, low visibility",setup:"9–11 ft bait rod, 20–30 lb braid or mono shock system, 40–60 lb leader, inline circle hook",rig:"fishfinder",knot:"improved-clinch",cast:["Read the first trough and cuts before choosing distance.","Use a smooth overhead cast with a shock leader rated for sinker weight.","Place the bait on the edge of moving water, not automatically beyond every breaker."],retrieve:["Keep the sinker anchored and enough tension to see a steady bend.","Check bait every 10–15 minutes or after strong wave action.","Move along the beach if no signs develop after several clean presentations."],hookset:"Leave the rod in the holder or hold steady; reel into the fish and let the circle hook turn.",mistakes:"Overcasting the fish, using too little sinker to hold, exposed hook points clogged with bait, or snap-setting."},
    {id:"fluke-bucktail",species:"fluke",title:"Bucktail a beach trough for fluke",when:"May through September on sand, cuts, inlet margins",setup:"7–9 ft medium rod, 10–20 lb braid, 20–30 lb leader; bucktail with scented trailer",rig:"fluke-bucktail",knot:"loop",cast:["Cast diagonally up-current into the first trough or across the lip of a cut.","Let the jig touch bottom and note the count."],retrieve:["Lift 8–12 inches, lower while recovering slack, and touch bottom again.","Walk slowly along the beach to cover the trough.","Pause beside depth changes where current slows."],hookset:"On weight or a moving stop, reel tight and make a firm sweeping lift.",mistakes:"Using too much weight, lifting several feet off bottom, or standing in the trough being fished."},
    {id:"fluke-fishfinder",species:"fluke",title:"Soak and sweep a fluke fish-finder rig",when:"NJ surf troughs, pier edges, and slower inlet margins during the open season",setup:"8–10 ft medium rod, 15–20 lb braid, 20–30 lb leader, 1–3 oz sinker, 1/0–3/0 hook, squid/spearing or legal bait",rig:"fluke-fishfinder",knot:"improved-clinch",cast:["Read the inner trough and cast just beyond its down-current lip.","Use a smooth lob or overhead cast so the bait does not helicopter off the hook.","Allow the sinker to settle, then take up slack without dragging it out of the lane."],retrieve:["Let current work the bait for 30–60 seconds.","Sweep the rig 2–3 feet with the rod, then reset and pause.","Repeat until the rig leaves the trough; recast at a new angle."],hookset:"When steady weight moves, reel down and sweep firmly while keeping the rod loaded.",mistakes:"Dead-sticking one patch too long, burying the hook point in bait, or using a sinker too heavy to move naturally."},
    {id:"fluke-inlet",species:"fluke",title:"Work a bucktail through an inlet rip",when:"Manasquan, Barnegat, Absecon, Cape May, and similar NJ inlet margins",setup:"8–9 ft medium-heavy rod, 20 lb braid, 30–40 lb leader, 1–4 oz bucktail matched to current",rig:"fluke-bucktail",knot:"loop",cast:["Stand only on legal stable access and identify the softer edge beside the main rip.","Cast 30 degrees up-current and let the jig reach bottom before it enters the seam.","Use the lightest jig that touches bottom repeatedly without tumbling."],retrieve:["Make short 6–10 inch lifts while following the sweep with the rod.","Recover slack as the jig falls so you can feel a pickup.","At the sand-rock transition, pause and shake the trailer in place."],hookset:"On heaviness, reel tight and sweep toward open water; keep pressure away from rock.",mistakes:"Casting into the fastest water, losing bottom contact, or wading an inlet channel."},
    {id:"bluefish-metal",species:"bluefish",title:"Cast metal to roaming bluefish",when:"Spring and fall runs, oceanfront feeds, inlet mouths",setup:"8–10 ft rod, 20–30 lb braid, 30–50 lb abrasion leader; metal jig or spoon",rig:"plug-leader",knot:"improved-clinch",cast:["Cast to the outer edge or ahead of the moving school, never across people.","Start the retrieve at splashdown to reduce bite-offs and tangles."],retrieve:["Use a fast steady retrieve for surface fish.","Count down and use lift-drop when fish sound below birds.","Keep the lure moving through the entire wash."],hookset:"Reel into the strike and sweep; maintain pressure through head shakes.",mistakes:"Using fingers near the mouth, wire that kills small-lure action without need, or stopping the lure in a school."},
    {id:"bluefish-popper",species:"bluefish",title:"Run a popper across a bluefish blitz",when:"Daylight surface feeds, mullet and peanut bunker, ocean beaches and inlet mouths",setup:"8–10 ft rod, 20–30 lb braid, abrasion leader, single-hook or simplified-hook popper where practical",rig:"plug-leader",knot:"loop",cast:["Cast ahead of the moving school or along its outside edge, never through crossing lines.","Start the lure at splashdown so fish cannot bite slack line."],retrieve:["Use fast, continuous pops while taking up every bit of slack.","If fish miss, keep moving rather than stopping in the school.","When feeds sink, switch to metal and count it down."],hookset:"Keep reeling until the rod loads, then sweep low and maintain firm pressure.",mistakes:"Stopping the lure after a miss, grabbing fish near the mouth, or using excess trebles in a crowd."},
    {id:"bluefish-bait",species:"bluefish",title:"Fish cut bait for bluefish safely",when:"Dirty surf, pier and inlet edges, schools beyond casting lures",setup:"Surf or pier rod, abrasion leader or short bite trace if cutoffs demand it, fish-finder rig, legal cut bait",rig:"fishfinder",knot:"improved-clinch",cast:["Use a controlled overhead cast to a trough edge or scent lane.","Keep people clear of the sinker arc and secure bait firmly."],retrieve:["Hold the sinker in place and keep light tension on the line.","Rebait after pickers or 10–15 minutes of washed-out scent.","Use long pliers before touching any hooked fish."],hookset:"For circle-hook bait rigs, reel steadily into the fish without a snap-set.",mistakes:"Using fingers near teeth, leaving a baited rod unattended, or failing to use a drop net from height."},
    {id:"sheeps-crab",species:"sheeps",title:"Drop a crab beside NJ structure",when:"Warm-water months on jetties, bridges, pilings, and seawalls",setup:"Medium-heavy sensitive rod, 20–30 lb braid, 20–30 lb abrasion leader, small sharp hook",rig:"sheeps-knocker",knot:"palomar",cast:["Lower vertically or make a short controlled pitch to the lee side of structure.","Stop the bait at the barnacle line or hard-soft edge."],retrieve:["Hold near-still with direct feel and the lightest sinker that stays in place.","After the first taps, wait for sustained heaviness or sideways movement.","Lift firmly and immediately steer away from barnacles."],hookset:"Firm upward lift on weight; with a circle hook, reel and lift without snapping.",mistakes:"Featureless open beach, dull hooks, heavy sinkers that hide bites, or failing to inspect the leader."},
    {id:"sheeps-dropshot",species:"sheeps",title:"Drop-shot a bridge or dock piling",when:"NJ bridge rails, bulkheads, and pilings with vertical public access",setup:"7 ft sensitive medium-heavy rod, 20 lb braid, 20–30 lb abrasion leader, small sharp hook, 1/2–2 oz sinker",rig:"sheeps-dropshot",knot:"palomar",cast:["Lower vertically beside the down-current face of the piling; do not pendulum-cast near traffic or people.","Stop the bait at the barnacle or mussel band, 6–18 inches above the sinker."],retrieve:["Hold direct contact and make tiny 1-inch shakes, not large jig strokes.","Move down the piling in one-foot increments.","On tap-tap, wait for sustained weight or sideways line movement."],hookset:"Lift firmly and immediately steer the fish away from the piling; reel-set when using a circle hook.",mistakes:"Fishing too far from structure, using a dull hook, or lifting a fish from height without a drop net."},
    {id:"sheeps-sandflea",species:"sheeps",title:"Pitch a sand flea where beach meets rock",when:"Warm-water months at inlet rock, seawalls, and sand-rock transitions",setup:"Medium spinning tackle, short 20–30 lb leader, small stout hook, compact sinker, fresh sand flea",rig:"sheeps-knocker",knot:"palomar",cast:["Make a short pitch to the lee pocket where sand meets submerged rock.","Let the sinker settle without wedging deeply into the stones."],retrieve:["Hold the bait nearly still and keep a slight bend in the tip.","Lift just enough to clear one rock, then reset in the next pocket.","Watch for line that moves sideways before the rod loads."],hookset:"Set on sustained weight and immediately use side pressure toward open water.",mistakes:"Treating sheepshead as an open-beach target, dragging across barnacles, or waiting after the fish turns into cover."},
  ],
  knots: {
    "palomar":{name:"Palomar",use:"Braid to a hook, jig, or swivel",steps:["Double 6 inches of line and pass the loop through the eye.","Tie a loose overhand knot with the doubled line.","Pass the hook or lure through the large loop.","Wet, pull standing line and tag evenly, then trim."],avoid:"Do not twist the doubled lines or let them cross at the eye.",video:{id:"TFk_Ktw2f1w",title:"Palomar Knot - Quick Tutorial on How to Tie This Strong Knot",channel:"Salt Strong"}},
    "improved-clinch":{name:"Improved clinch",use:"Mono or fluoro to a hook, swivel, or lure",steps:["Pass 6 inches through the eye and wrap the tag around the standing line 5–7 times.","Pass the tag through the small loop beside the eye.","Pass the tag back through the large loop just formed.","Wet thoroughly, pull slowly to seat, inspect, and trim."],avoid:"Not the first choice for slick braid; use a Palomar for braid.",video:{id:"fXWRZe784QU",title:"Fishing Knots: How to Tie an Improved Clinch Knot",channel:"Take Me Fishing"}},
    "loop":{name:"Non-slip loop",use:"Free-swinging bucktails, soft plastics, and plugs",steps:["Tie a loose overhand knot 6 inches from the tag end.","Pass the tag through the lure eye, then back through the overhand knot.","Wrap the tag around the standing line 4–5 times.","Return through the overhand knot from the same side, wet, seat, and trim."],avoid:"Keep the finished loop small so it cannot catch hooks or hardware.",video:{id:"C0u5HQBiv_I",title:"How To Tie A Non-Slip Loop Knot (Quick, Easy, & Strong Fishing Knot)",channel:"Salt Strong"}},
    "double-uni":{name:"Double uni",use:"Braid to mono or fluoro leader",steps:["Overlap main line and leader by 8 inches.","Form a loop with the leader tag and wrap through it 5 times.","Repeat with braid, using 7–8 wraps.","Wet, pull standing lines to slide knots together, then trim close."],avoid:"Do not use too few wraps on thin braid; test the connection hard before casting.",video:{id:"6VgQLBpwJUY",title:"Fishing Knots: Double Uni Knot - How to Tie Braid to Fluorocarbon or Braid to Mono",channel:"Fishthatwontquit"}},
    "dropper-loop":{name:"Dropper loop",use:"Attach a teaser or hook above a jig or sinker",steps:["Form a 6-inch loop in the leader at the desired location.","Twist the loop around both leader strands 5–7 times.","Open the center twist and pull the original loop through.","Wet and pull both standing ends evenly to lock the loop."],avoid:"Keep the dropper short and use one teaser in crowded surf.",video:{id:"zDYQ-oIDbUo",title:"How To Tie A Dropper Loop Knot [Fast & Easy Way]",channel:"Salt Strong"}}
  },
  rigs: {
    "plug-leader":{name:"Plug leader",parts:["Braid main line","Double-uni or Alberto connection","24–40 in mono/fluoro leader","Small clip or direct loop knot","Plug"]},
    "jighead":{name:"Soft-plastic jighead",parts:["Braid","Leader connection","24–40 in leader","Loop knot","Jighead with plastic rigged straight"]},
    "bucktail-teaser":{name:"Bucktail and teaser",parts:["Braid","40 lb leader","Dropper loop 12–18 in above jig","Single teaser hook","Bucktail at leader end"]},
    "fishfinder":{name:"Fish-finder bait rig",parts:["Main line","Sinker slide and sinker","Bead","Barrel swivel","18–36 in leader","Inline circle hook"]},
    "live-bait":{name:"Live eel or bunker rig",parts:["Braid","Leader connection or swivel","30–50 in abrasion leader","Inline circle hook","Live bait with hook point exposed"]},
    "fluke-bucktail":{name:"Fluke bucktail and teaser",parts:["Braid","20–30 lb leader","Optional short dropper and teaser","Bucktail","Scented trailer or strip bait"]},
    "fluke-fishfinder":{name:"Fluke fish-finder rig",parts:["Main line","Sinker slide and sinker","Bead","Barrel swivel","20–30 lb leader","1/0–3/0 hook and bait"]},
    "sheeps-knocker":{name:"Sheepshead knocker rig",parts:["Main line","Egg sinker","Short 20–30 lb abrasion leader","Small strong hook","Crab, shrimp, or sand flea"]},
    "sheeps-dropshot":{name:"Sheepshead drop-shot rig",parts:["Braid main line","20–30 lb abrasion leader","Palomar-tied small hook","6–18 in tag below hook","1/2–2 oz sinker","Crab or shrimp"]}
  },
  hotspots: [
    {id:"sandy-hook",name:"Sandy Hook / Raritan Bay",region:"North Jersey",species:["striper","fluke","bluefish"],season:"Spring and fall stripers/bluefish; summer fluke",access:"Gateway National Recreation Area beaches and bay shoreline. After-hours fishing parking requires the current NPS Fishing Access Pass; 2026 passes are sold out.",habitat:"Bay points, ocean troughs, rips, sand bars, and moving bait around the Hook.",cast:"Work the first trough, points, and current seams; do not assume distance is the answer.",conditions:"Moving water and low light; bay warming favors spring, ocean bait favors fall.",first:"Bucktail or paddletail for stripers; bucktail and scented trailer for fluke; metal for bluefish.",safety:"Fishing is prohibited on guarded swim beaches while lifeguards are on duty and within posted shorebird closures. Verify NPS parking and hours.",source:"https://www.nps.gov/gate/planyourvisit/fishing.htm"},
    {id:"monmouth-beaches",name:"Monmouth County ocean beaches",region:"North-Central Jersey",species:["striper","fluke","bluefish"],season:"Spring/fall migration; summer fluke; episodic bluefish",access:"Use legal municipal beach access and current seasonal parking rules. Fishing restrictions vary during guarded swimming hours.",habitat:"Troughs, cuts, points, jetties, and storm-created bars from Sea Bright south.",cast:"Walk at low tide to locate dark cuts and deeper troughs, then return on moving water.",conditions:"Onshore or side wind that is fishable can push bait close; avoid unsafe heavy surf.",first:"Minnow plug or bucktail for bass; light bucktail for fluke; metal for blues.",safety:"Check town beach rules, badges, night parking, and guarded-area restrictions before fishing.",source:"https://www.nj.gov/dep/parksandforests/"},
    {id:"shark-river",name:"Shark River Inlet area",region:"Monmouth County",species:["striper","fluke","bluefish"],season:"Spring through fall; night bass in warm months",access:"Public access and parking are municipal and can change. Verify Belmar and Avon rules before arrival.",habitat:"Inlet throat, bridge shadow, sand-rock transition, and ocean wash.",cast:"Cast up-current and sweep the seam; for fluke, keep a bucktail on the sand-rock edge.",conditions:"First and last portions of moving tide are easier to control than peak flow.",first:"Bucktail, paddletail, or minnow plug; metal when blues are present.",safety:"Strong current, traffic, wet rock, hooks, and night visibility require flotation and traction.",source:"https://www.nj.gov/dep/fgw/marine.htm"},
    {id:"manasquan",name:"Manasquan Inlet",region:"Ocean / Monmouth border",species:["striper","fluke","bluefish","sheeps"],season:"Bass and blues spring/fall; fluke summer; sheepshead warm months",access:"Use established public inlet and beach access only; verify Point Pleasant Beach and Manasquan parking and jetty restrictions.",habitat:"Jetty pockets, inlet rip, bridge current, sand-rock base, and bait exiting the river.",cast:"Quarter up-current with bucktails; drop crabs vertically on the lee side of barnacled structure.",conditions:"Moderate moving tide; avoid peak current when bottom contact or footing becomes unsafe.",first:"Bucktail for bass/fluke, metal for blues, crab on a knocker rig for sheepshead.",safety:"Never fish closed jetty sections or climb barriers. Waves can sweep exposed rock without warning.",source:"https://www.nj.gov/dep/parksandforests/"},
    {id:"ibsp-barnegat",name:"Island Beach State Park / Barnegat Inlet",region:"Ocean County",species:["striper","fluke","bluefish","sheeps"],season:"Spring/fall bass and blues; May–September fluke; late-summer sheepshead",access:"State park entrance, hours, beach driving, and Mobile Sport Fishing Vehicle permits apply. Check current IBSP rules before travel.",habitat:"Long beach troughs, cuts, inlet jetty, pocket water, sand-rock edge, and bay-side current.",cast:"Beach: fish the first trough and cuts. Inlet: cast up-current along seams. Sheepshead: vertical crab tight to rock.",conditions:"Rising surf tide for troughs; controlled moving inlet water for jigs and structure bait.",first:"Bucktail or minnow plug for bass; bucktail/Gulp-style trailer for fluke; metal for blues; crab for sheepshead.",safety:"Respect guarded swim areas, vehicle zones, park closures, plover protection, and jetty conditions.",source:"https://nj.gov/dep/parksandforests/parks/islandbeachstatepark.html"},
    {id:"absecon",name:"Absecon Inlet / Atlantic City",region:"Atlantic County",species:["striper","fluke","bluefish","sheeps"],season:"Spring–fall mixed fishery; warm-water sheepshead",access:"Use designated public frontage, jetties, bulkheads, or municipal access. Verify parking and any closed structure before fishing.",habitat:"Deep inlet current, bridge/piling shade, riprap, seawalls, and adjacent beach cuts.",cast:"Sweep lures through current edges; fish fluke along the base; present crab vertically beside encrusted structure.",conditions:"Moving tide with a fishable current speed; nighttime shadow lines for bass.",first:"Bucktail or paddletail, fluke rig, metal jig, or crab depending on species.",safety:"Urban traffic, railings, height, boat traffic, slippery rock, and night visibility require planning and a drop net.",source:"https://www.atlanticcitynj.com/"},
    {id:"great-egg-corsons",name:"Great Egg Harbor / Corsons Inlet",region:"Cape May / Atlantic counties",species:["striper","fluke","bluefish"],season:"Spring/fall bass and blues; summer fluke",access:"Corsons Inlet State Park and nearby municipal access have changing hours, parking, and protected-area restrictions.",habitat:"Inlet banks, sand points, creek mouths, marsh drains, and channel edges.",cast:"Fish down-current lips and creek mouths; move with the tide rather than anchoring one dead area.",conditions:"Falling water concentrates forage at drains; incoming water activates beach troughs.",first:"Paddletail or bucktail for bass, bottom-contact bucktail for fluke, metal for bluefish.",safety:"Soft sand, deep cuts, rapid current, boats, and seasonal bird closures. Avoid crossing channels on foot.",source:"https://www.nj.gov/dep/parksandforests/parks/corsonsinletstatepark.html"},
    {id:"cape-may",name:"Cape May Inlet and Canal area",region:"Cape May County",species:["striper","fluke","bluefish","sheeps"],season:"Long spring/fall migration; summer fluke; late-summer sheepshead",access:"Use public beaches, state-managed areas, and legal canal/inlet access. Verify municipal parking, USCG/security boundaries, and private property.",habitat:"Inlet rip, canal current, bridge pilings, rock walls, beachfront troughs, and Delaware Bay transition.",cast:"Cast along rather than onto structure; cover current seams and bottom edges; drop crab beside pilings.",conditions:"Moving tide and temperature transitions between bay and ocean.",first:"Bucktail/minnow plug for bass, fluke bucktail, metal for blues, small crab for sheepshead.",safety:"Do not enter restricted Coast Guard or private areas. Current, boat wakes, and rock height require caution.",source:"https://www.capemaycity.com/"},
    {id:"delaware-bayshore",name:"Delaware Bayshore public beaches",region:"Cumberland / Cape May counties",species:["striper","fluke","bluefish"],season:"Spring striped bass and drum overlap; summer fluke; fall bass/blues",access:"Use named public beaches, wildlife-management access, or municipal landings only. Verify site hours, wildlife closures, and road conditions.",habitat:"Sloping sand, creek mouths, channel edges, points, shell bottom, and warming shallow water.",cast:"Target creek outflows and depth changes; bait rigs need enough sinker to hold without burying.",conditions:"Spring warming and moving tide; wind can expose or flood access roads.",first:"Paddletail/bucktail or legal bait for bass, light fluke rig in channels, metal for blues.",safety:"Remote mud, insects, tides, soft shoulders, and limited cellular coverage. Tell someone the plan.",source:"https://dep.nj.gov/njfw/conservation/delaware-bay/"}
  ],
  brandLinks: {
    penn:{label:"PENN",url:"https://www.pennfishing.com/"},
    "jigging-world":{label:"Jigging World",url:"https://www.jiggingworld.com/"},
    shimano:{label:"Shimano",url:"https://fish.shimano.com/"},
    daiwa:{label:"Daiwa",url:"https://daiwa.us/"}
  },
  setupProfiles: {
    "surf-light":{
      name:"Light surf and plugs",
      tiers:[
        {tier:"budget",label:"Budget",brand:"penn",rod:"Battle IV combo, 8 ft Medium Heavy, Moderate Fast, 3/4–2 oz",reel:"PENN Battle IV 5000, 5.6:1, 25 lb max drag",reelOptions:["PENN Battle IV 5000","Shimano Spheros SW 5000","Daiwa BG MQ 5000"],line:"20–30 lb braid · 30–40 lb leader",fit:"A durable entry combo for bucktails, swimmers, tins, pencils, poppers, and beach fluke inside its lure rating.",url:"https://www.pennfishing.com/products/battle-iv-spinning-rod-and-reel-combo-1624413"},
        {tier:"mid",label:"Mid-tier",brand:"jigging-world",rod:"Onyx Surf JW-ONYX902-M, 9 ft Medium, 3/4–2 oz",reel:"Shimano Spheros SW 5000",reelOptions:["PENN Battle IV 4000/5000","Shimano Spheros SW 5000","Daiwa BG MQ 4000/5000"],line:"20 lb braid · 25–40 lb leader",fit:"Lightweight surf coverage for repeated casting when most offerings stay at or below 2 oz.",url:"https://www.jiggingworld.com/products/jigging-world-onyx-surf-rods"},
        {tier:"high",label:"High-tier",brand:"jigging-world",rod:"Nexus Surf JW-NXS902S-M, 9 ft Medium, 1/2–2 oz",reel:"Daiwa Saltist MQ 5000",reelOptions:["PENN Spinfisher VII 4500","Shimano Spheros SW 5000","Daiwa Saltist MQ 5000"],line:"20–30 lb braid · 30–40 lb leader",fit:"A specialist all-weather plugging system with a broader low-end lure window and sealed reel platform.",url:"https://www.jiggingworld.com/products/jigging-world-nexus-surf-rods"}
      ]
    },
    "surf-medium":{
      name:"Medium surf and current",
      tiers:[
        {tier:"budget",label:"Budget",brand:"penn",rod:"Battle IV combo, 9 ft Medium Heavy, Moderate Fast, 1–3 oz",reel:"PENN Battle IV 6000, 5.6:1, 25 lb max drag",reelOptions:["PENN Battle IV 6000","Shimano Spheros SW 5000/6000","Daiwa BG MQ 5000/6000"],line:"30 lb braid · 30–50 lb leader",fit:"Entry current-and-whitewater setup for bucktails, darters, needles, poppers, metals, and bluefish.",url:"https://www.pennfishing.com/products/battle-iv-spinning-rod-and-reel-combo-1624413"},
        {tier:"mid",label:"Mid-tier",brand:"jigging-world",rod:"Onyx Surf JW-OX962S-MH, 9 ft 6 in Medium Heavy, 3/4–3 oz",reel:"Shimano Spheros SW 5000",reelOptions:["PENN Spinfisher VII 4500/5500","Shimano Spheros SW 5000/6000","Daiwa BG MQ 5000"],line:"20–30 lb braid · 30–50 lb leader",fit:"Verified 3/4–3 oz range for repeated lure casting and controlled current work.",url:"https://www.jiggingworld.com/products/jigging-world-onyx-surf-rods"},
        {tier:"high",label:"High-tier",brand:"jigging-world",rod:"Nexus Surf JW-NXS962S-MH, 9 ft 6 in Medium Heavy, 3/4–3 oz",reel:"Daiwa Saltist MQ 5000",reelOptions:["PENN Slammer IV 4500/5500","Shimano Saragosa SW 5000/6000","Daiwa Saltist MQ 5000"],line:"30 lb braid · 40–50 lb leader",fit:"Specialist 70/30 surf blank for inlet seams and heavy plugging within the 3 oz ceiling.",url:"https://www.jiggingworld.com/products/jigging-world-nexus-surf-rods"}
      ]
    },
    "surf-heavy":{
      name:"Heavy surf and bait",
      tiers:[
        {tier:"budget",label:"Budget",brand:"penn",rod:"Battle IV combo, 10 ft Heavy, Moderate Fast, 1–5 oz",reel:"PENN Battle IV 8000, 4.7:1, 30 lb max drag",reelOptions:["PENN Battle IV 8000","Shimano Saragosa SW 8000","Daiwa Saltist MQ 6000"],line:"40–50 lb braid · shock/leader matched to sinker",fit:"An entry heavy-surf combo for larger swimmers, eels, bunker, clam, and fish-finder rigs within the 5 oz ceiling.",url:"https://www.pennfishing.com/products/battle-iv-spinning-rod-and-reel-combo-1624413"},
        {tier:"mid",label:"Mid-tier",brand:"penn",rod:"Squadron IV Surf, 10 ft Medium Heavy, Moderate Fast, 1–5 oz",reel:"Shimano Saragosa SW 6000",reelOptions:["PENN Battle IV 6000","Shimano Saragosa SW 6000","Daiwa BG MQ 6000"],line:"30–40 lb braid · 40–60 lb leader",fit:"A balanced bait-and-heavy-plug option with verified 1–5 oz casting range.",url:"https://www.pennfishing.com/products/squadron-iv-surf-spinning-rod"},
        {tier:"high",label:"High-tier",brand:"jigging-world",rod:"Nexus Surf JW-NXS1002S-H, 10 ft Heavy, 2–5 oz",reel:"Daiwa Saltist MQ 6000",reelOptions:["PENN Slammer IV 5500/6500","Shimano Saragosa SW 6000/8000","Daiwa Saltist MQ 6000"],line:"30–40 lb braid · 40–60 lb leader",fit:"Premium heavy plugging and moderate bait work inside the verified 2–5 oz rod range; use a dedicated heavier bait rod when the complete sinker-and-bait payload exceeds 5 oz.",url:"https://www.jiggingworld.com/products/jigging-world-nexus-surf-rods"}
      ]
    },
    "inshore-light":{
      name:"Light inshore and finesse",
      tiers:[
        {tier:"budget",label:"Budget",brand:"penn",rod:"Battle IV combo, 7 ft Medium, Fast, 1/4–1 oz",reel:"PENN Battle IV 4000, 6.2:1, 15 lb max drag",reelOptions:["PENN Battle IV 3000/4000","Shimano Stradic FM 3000/4000","Daiwa BG 3000/4000"],line:"15–20 lb braid · 20–30 lb leader",fit:"A ready-to-fish platform for bay paddletails, light fluke jigs, and finesse structure work.",url:"https://www.pennfishing.com/products/battle-iv-spinning-rod-and-reel-combo-1624413"},
        {tier:"mid",label:"Mid-tier",brand:"penn",rod:"Battalion II Inshore BATINII1017S76, 7 ft 6 in Medium, Fast, 1/4–1 oz",reel:"Shimano Stradic FM 3000/4000",reelOptions:["PENN Battle IV 3000/4000","Shimano Stradic FM 3000/4000","Daiwa BG 3000/4000"],line:"15–20 lb braid · 20–30 lb leader",fit:"More sensitivity and reach for fluke troughs, light jigheads, and subtle sheepshead bites.",url:"https://www.pennfishing.com/products/battalion-ii-inshore-spinning-rod"},
        {tier:"high",label:"High-tier",brand:"jigging-world",rod:"Night Ranger JW-NR721S-MH, 7 ft 2 in Medium Heavy, 1/2–1.5 oz",reel:"Daiwa BG MQ 3000/4000",reelOptions:["PENN Spinfisher VII 3500","Shimano Stradic FM 4000","Daiwa BG MQ 3000/4000"],line:"20 lb braid · 20–30 lb leader",fit:"A premium inshore system for the heavier half of finesse work; choose the mid-tier rod when consistently fishing below 3/4 oz.",url:"https://www.jiggingworld.com/products/jigging-world-night-ranger-rods"}
      ]
    },
    "inshore-heavy":{
      name:"Heavy inshore and structure",
      tiers:[
        {tier:"budget",label:"Budget",brand:"penn",rod:"Battle IV combo, 7 ft Medium Heavy, Fast, 1/2–1.5 oz",reel:"PENN Battle IV 5000, 5.6:1, 25 lb max drag",reelOptions:["PENN Battle IV 5000","Shimano Spheros SW 5000","Daiwa BG MQ 5000"],line:"20–30 lb braid · 30–50 lb leader",fit:"Strong entry setup for inlet edges, bluefish bait, live bunker, and pulling fish away from structure.",url:"https://www.pennfishing.com/products/battle-iv-spinning-rod-and-reel-combo-1624413"},
        {tier:"mid",label:"Mid-tier",brand:"penn",rod:"Battalion II Inshore BATINII1530S70, 7 ft Heavy, Fast, 3/4–2.5 oz",reel:"Shimano Saragosa SW 5000/6000",reelOptions:["PENN Battle IV 5000","Shimano Saragosa SW 5000/6000","Daiwa BG MQ 5000"],line:"30 lb braid · 30–50 lb leader",fit:"A sensitive but powerful structure and current setup for heavier jigs and bait presentations.",url:"https://www.pennfishing.com/products/battalion-ii-inshore-spinning-rod"},
        {tier:"high",label:"High-tier",brand:"jigging-world",rod:"Nexus 2.0 JW-NEX701S-MH, 7 ft Medium Heavy, 1–4 oz",reel:"Daiwa Saltist MQ 5000",reelOptions:["PENN Slammer IV 4500","Shimano Saragosa SW 5000/6000","Daiwa Saltist MQ 5000"],line:"30–40 lb braid · 40–60 lb leader",fit:"Specialist current-and-structure system with a broad verified lure range and higher drag reserve.",url:"https://www.jiggingworld.com/products/jigging-world-nexus-2-0-rods"}
      ]
    }
  },
  setupMap: {
    "striper-bucktail":"surf-medium","striper-paddletail":"surf-light","striper-minnow":"surf-light","striper-pencil":"surf-light","striper-popper":"surf-medium","striper-tin":"surf-heavy",
    "striper-metallip":"surf-heavy","striper-needle":"surf-medium","striper-darter":"surf-medium","striper-eel":"surf-heavy","striper-bunker":"surf-heavy","striper-clam":"surf-heavy",
    "fluke-bucktail":"inshore-light","fluke-fishfinder":"surf-medium","fluke-inlet":"inshore-heavy",
    "bluefish-metal":"surf-medium","bluefish-popper":"surf-medium","bluefish-bait":"surf-heavy",
    "sheeps-crab":"inshore-light","sheeps-dropshot":"inshore-light","sheeps-sandflea":"inshore-light"
  },
  regulations: [
    {species:"Striped bass",summary:"Atlantic Ocean 0–3 nm: year-round, 28–31 in, 1 fish. Other marine waters: Mar 1–Dec 31. Delaware River zones differ. Inline circle hooks required with bait; EEZ closed.",source:"https://www.eregulations.com/newjersey/fishing/saltwater/state-size-possession-limits"},
    {species:"Fluke",summary:"May 4–Sep 25. General waters 18 in/3 fish; Delaware Bay 17 in/3; IBSP shore 16 in/2.",source:"https://www.eregulations.com/newjersey/fishing/saltwater/state-size-possession-limits"},
    {species:"Bluefish",summary:"No closed season or minimum size. 5 fish for most anglers; 7 from qualifying party/charter vessels.",source:"https://www.eregulations.com/newjersey/fishing/saltwater/state-size-possession-limits"},
    {species:"Sheepshead",summary:"Not listed in the 2026 NJ regulated-species table; no minimum, bag, or season is listed. Wanton-waste rules still apply.",source:"https://www.eregulations.com/newjersey/fishing/saltwater/state-size-possession-limits"}
  ]
};